spring:
  redis:
    host: cybvpeou06
    port: 6379
    password: null
    pool:
      max-idle: 300
      min-idle: 10
      max-active: 600
      max-wait: 1000
    timeout: 0

logging:
  level:
    org.springframework.web: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"